export const actionTypes = {
    GET_USER_OBJECTS: "GET_USER_OBJECTS",
    CREATE_USER_OBJECTS: "CREATE_USER_OBJECTS",
    DELETE_USER_OBJECTS: "DELETE_USER_OBJECTS",
    SELECTED_USER_OBJECTS: "SELECTED_USER_OBJECTS",
    
    LOGIN_USER: "LOGIN_USER"
}